### ISSUE TITLE
Config synchronization and encryption

### ISSUE THREAD

**Issue by clexanis** [clexanis/cloud-server#1]
## Tasks

- [ ] Define how standard configuration are stored (.env?).
- [ ] Define how secure configuration are stored.
- [ ] Implement config auto-synchronization (with a git repo?).
- [ ] Implement config encryption for sensitive data.

### Auto sync to a git repo
  - [git-sync](https://github.com/simonthum/git-sync)
  - [git-auto-sync](https://github.com/GitJournal/git-auto-sync)

### Encryption
  - [git-crypt](https://github.com/AGWA/git-crypt)
  - [git-remote-gcrypt](https://github.com/spwhitton/git-remote-gcrypt)
